name: Publish PKG

on: pull_request
jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      PROJECT_PATH: 'DotnetViewComponents/DotnetViewComponents.csproj'
    name: Build, Pack, and Publish NuGet Package
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy: 
      matrix:
        dotnet-version: ['3.1.x']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore NuGet packages
        run: |
          dotnet restore ${{ env.PROJECT_PATH }}
          echo "Restored --> ${{ env.PROJECT_PATH }}"

      # - name: Build solution
      #   run: |
      #     dotnet build ${{ env.PROJECT_PATH }} --configuration ${{ env.BUILD_CONFIG }} --no-restore
      #     echo "Built --> ${{ env.PROJECT_PATH }}"

      # - name: Pack NuGet package
      #   run: |
      #     dotnet pack ${{ env.PROJECT_PATH }} --configuration ${{ env.BUILD_CONFIG }} --no-build -o out /p:PackageVersion="1.1.2"
      #     echo "Built --> ${{ env.PROJECT_PATH }}"

      - name: Add GitHub NuGet source
        run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name githubPackages "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Dotnet build
        run: dotnet build nhsuk-frontend-tel.sln --configuration release

      - name: Package nuget        
        run: dotnet pack nhsuk-frontend-tel.sln --configuration release -o package /p:PackageVersion="1.0.3"

      - name: Push generated package to GitHub registry
        if: startsWith(github.ref, 'refs/tags/v')
        run: dotnet nuget push ./package/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source "githubPackages" --skip-duplicate

      # - name: Publish NuGet package to GitHub Packages
      #   run: dotnet nuget push out/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
