name: Continuous Integration

on: [push]

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'DotnetViewComponents.sln'
    name: Build and publish package
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        dotnet-version: ['3.1.x']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install ICU library
        run: sudo apt-get update && sudo apt-get install -y libicu-dev

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}


      - name: Add GitHub registry
        run: dotnet nuget add source --username 'dalin.akrasi' --password ${{ secrets.PULLREQUEST_TOKEN }} --store-password-in-clear-text --name githubPackages "https://nuget.pkg.github.com/TechnologyEnhancedLearning/index.json"

      - name: Dotnet build
        run: dotnet build DotnetViewComponents.sln --configuration release

      - name: Package nuget
        run: dotnet pack DotnetViewComponents.sln --configuration release -o:package /p:PackageVersion=${{ 14.3 }}

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./package/*.nupkg --api-key ${{ secrets.PULLREQUEST_TOKEN }} --source "githubPackages" --skip-duplicate
