name: Publish NuGet Package

on: [push, pull_request]
jobs:
  version-bump:
    name: Bump test
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch latest NuGet version from GitHub Packages
        id: latest_nuget_version
        env:
          REPO: "main"
          NUGET_PACKAGE: "DotnetViewComponents"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
        run: |
          echo "Fetching latest NuGet version for $NUGET_PACKAGE in $REPO"
          VERSIONS_JSON=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/users/$OWNER/packages/nuget/$NUGET_PACKAGE/versions")
          LATEST_VERSION=$(echo "$VERSIONS_JSON" | jq -r '.[0].name')
          echo "Latest NuGet package version: $LATEST_VERSION"
          echo "::set-output name=version::$LATEST_VERSION"


      #################################################
      # 1. Get latest release version (git-based or release-based)
      #################################################
      - name: Get latest release version
        id: current_version
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          # This Action is maintained, used by many, and updated recently (Jul 2025)[3][15]
      - name: Echo latest version
        run: echo "Current version:${{ steps.current_version.outputs.version }}"

      #################################################
      # 2. Decide increment type: patch, minor, major
      #################################################
      - name: Set increment type based on branch and labels
        id: increment_type
        run: |
          BRANCH_REF="${{ github.head_ref }}"
          MERGE_MESSAGE="${{ github.event.pull_request.title }} ${{ github.event.pull_request.body }}"
          LABELS="${{ join(github.event.pull_request.labels.*.name, ',') }}"
          TYPE="patch"

          echo "Branch: $BRANCH_REF"
          echo "Merge message: $MERGE_MESSAGE"
          echo "Labels: $LABELS"

          if [[ "$LABELS" == *"Major"* ]] || [[ "$MERGE_MESSAGE" =~ MAJOR ]] || [[ "$MERGE_MESSAGE" =~ BREAKING[[:space:]]CHANGE ]]; then
            TYPE="major"
          elif [[ "$BRANCH_REF" == feature/* ]]; then
            TYPE="minor"
          elif [[ "$BRANCH_REF" == fix/* ]]; then
            TYPE="patch"
          fi

          # Major version increase option: if the new tag with different 'major' was just created in this PR
          NEW_MAJOR_TAG=""
          git fetch --tags
          LATEST_MAJOR="$(echo ${{ steps.current_version.outputs.version }} | cut -d'.' -f1)"
          for tag in $(git tag 'v*'); do
            TAG_MAJOR="$(echo $tag | cut -d'.' -f1 | sed 's/v//')"
            if [[ "$TAG_MAJOR" -gt "$LATEST_MAJOR" ]]; then
              NEW_MAJOR_TAG="$tag"
              break
            fi
          done

          if [[ "$NEW_MAJOR_TAG" != "" ]]; then
            TYPE="major"
            echo "Detected new major tag: $NEW_MAJOR_TAG"
          fi

          echo "Will increment: $TYPE"
          echo "::set-output name=TYPE::$TYPE"

      #################################################
      # 3. Bump new semantic version
      #################################################
      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.2.3
        with:
          current-version: ${{ steps.current_version.outputs.version }}
          version-fragment: ${{ steps.increment_type.outputs.TYPE }}

      - name: Echo new version
        run: echo "Next version:${{ steps.bump_version.outputs.next-version }}"
          

  nuget_publish:
    name: Build, Pack, and Publish NuGet Package
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      BUILD_CONFIG: "Release"
      PROJECT_PATH: "DotnetViewComponents/DotnetViewComponents.csproj"
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'   # Specify your target .NET version

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.0.1
        with:
          versionSpec: '6.3.0'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4.0.1

      - name: Display versioning outputs
        run: |
          echo "NuGet Version: ${{ steps.gitversion.outputs.nuGetVersionV2 }}"
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
          echo "Outputs: ${{ toJson(steps.gitversion.outputs) }}"

      - name: Use version in another step
        run: |
          VERSION="${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Restore NuGet packages
        run: dotnet restore $PROJECT_PATH

      - name: Build project
        run: dotnet build $PROJECT_PATH --configuration $BUILD_CONFIG --no-restore

      - name: Pack NuGet package
        run: dotnet pack $PROJECT_PATH --configuration $BUILD_CONFIG --no-build -o out /p:PackageVersion=$VERSION

      - name: Add GitHub NuGet source
        run: dotnet nuget add source --username ${{ github.actor }} --password $GITHUB_TOKEN --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Publish NuGet package to GitHub Packages
        run: dotnet nuget push out/*.nupkg --api-key $GITHUB_TOKEN --source "github" --skip-duplicate
