name: Publish NuGet Package

on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetches all history for GitVersion to analyze

      - name: 'Install GitVersion'
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: 'Determine Version'
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15

      - name: 'Setup .NET'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: 'Build and Pack'
        run: |
          dotnet build ${{ env.PROJECT_PATH  }} --configuration Release
          dotnet pack ${{ env.PROJECT_PATH  }} --configuration Release -p:Version=${{ steps.gitversion.outputs.semVer }} -o ./output

      - name: 'Publish to GitHub Packages'
        run: dotnet nuget push "./output/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}"
